name: Build and Push Docker image with Firebase credentials

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Criar arquivo de credenciais do Firebase
        run: echo "${{ secrets.FIREBASE_CREDENTIALS }}" > firebase-key.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t brunobomfim/minha-api-fastapi:latest .

      - name: Push Docker image
        run: docker push brunobomfim/minha-api-fastapi:latest
